# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Juliette Sinibardy
description: >-
  Pending Programmer<br>
  ███░░░░░░░ 30%
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsinibardy.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Juliette Sinibardy
lang: en_US
timezone: Europe/Paris

linkedin: juliette-sinibardy
github_username: jsiny
medium_username: juju.siny

markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - github-pages
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

paginate: 5
paginate_path: '/page/:num'

sidebar_home_link: true
enable_disqus: false
# sidebar_blog_link: '/blog'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_compose:
  draft_default_front_matter:
    description:
    image:
    category:
    tags:
  post_default_front_matter:
    last_modified_at: 
    permalink: 
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags:

