# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Juliette Sinibardy
description: >-
  Pending Programmer
  ████░░░░░░░░░ 30%
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin: juliette-sinibardy
github_username: jsiny
medium_username: juju.siny

markdown: kramdown
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - github-pages
  - jemoji

paginate: 5
paginate_path: '/page/:num'

sidebar_home_link: true
# sidebar_blog_link: '/blog'
enable_disqus: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
